version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: "increase"
    commit-message:
      prefix: "chore"
    directory: "/sites/blog"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      npm-blog:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    versioning-strategy: "increase"
    commit-message:
      prefix: "chore"
    directory: "/sites/home"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      npm-home:
        patterns:
          - "*"
