version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: "increase"
    commit-message:
      prefix: "chore"
    directory: "/blog.k1f0.dev"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      blog.k1f0.dev:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    versioning-strategy: "increase"
    commit-message:
      prefix: "chore"
    directory: "/k1f0.dev"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      k1f0.dev:
        patterns:
          - "*"
