version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: "increase"
    commit-message:
      prefix: "chore"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      all:
        patterns:
          - "*"
