apiVersion: v1
kind: Pod
metadata:
  name: k1f0.dev
spec:
  restartPolicy: Always
  containers:
    - name: k1f0dev
      image: k1f0.dev:latest
      resources:
        limits:
          memory: "1G"
      env:
        - name: TZ
          value: Europe/Vienna
      ports:
        - containerPort: 80
          hostIP: 127.0.0.1
          hostPort: 3080
