apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  securityContext:
    fsGroup: 1000
    privileged: false
    readOnlyRootFilesystem: false
  containers:
  - name: k1f0.dev
    image: k1f0.dev:latest
    env:
    - name: TZ
      value: Europe/Vienna
    - name: CONFIG
      value: /config/config.json
    ports:
    - containerPort: 8080
      hostIP: 127.0.0.1
      hostPort: 8881
    volumeMounts:
    - mountPath: /config
      name: data-k1f0.dev
    - mountPath: /icons
      name: data-icons
  - name: blog.k1f0.dev
    image: blog.k1f0.dev:latest
    env:
    - name: TZ
      value: Europe/Vienna
    - name: POSTS_PATH
      value: /posts
    - name: DB_HOST
      value: valkey
    ports:
    - containerPort: 80
      hostIP: 127.0.0.1
      hostPort: 8880
    volumeMounts:
    - mountPath: /config
      name: data-blog.k1f0.dev
    - mountPath: /posts
      name: data-posts
  - name: valkey
    image: docker.io/valkey/valkey:8-alpine
    args:
    - valkey-server
    - --save 60 1
    - --loglevel warning
    env:
    - name: TZ
      value: Europe/Vienna
    volumeMounts:
    - mountPath: /data
      name: data-valkey
  volumes:
  - hostPath:
    path: ./.data/database
    type: DirectoryOrCreate
    name: data-valkey
  - hostPath:
    path: ./.data/posts
    type: DirectoryOrCreate
    name: data-posts
  - hostPath:
    path: ./.data/icons
    type: DirectoryOrCreate
    name: data-icons
  - hostPath:
    path: ./.data/k1f0.dev
    type: DirectoryOrCreate
    name: data-k1f0.dev
  - hostPath:
    path: ./.data/blog.k1f0.dev
    type: DirectoryOrCreate
    name: data-blog.k1f0.dev
