apiVersion: v1
kind: Pod
metadata:
  name: k1f0.dev
  annotations:
    io.podman.annotations.userns: keep-id
spec:
  containers:
  - name: database
    image: docker.io/valkey/valkey:8-alpine
    env:
    - name: TZ
      value: Europe/Vienna
    ports:
    - containerPort: 6379
      hostIP: 127.0.0.1
      hostPort: 6379
