version: '3'
services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8085"
    environment:
      - TZ=Europe/Vienna
    restart: unless-stopped
