version: '3'
services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: astro
    volumes:
      - ./data:/var/lib/denokv:Z
    environment:
      TZ: Europe/Vienna
    ports:
      - 127.0.0.1:8085:8085
    restart: unless-stopped