version: '3'
services:
  mongo:
    image: mongo
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: CHANGEME
      MONGO_INITDB_ROOT_PASSWORD: CHANGEME
    volumes:
      - ./data/db:/data/db
    restart: unless-stopped

  astro:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: astro
    ports:
      - '127.0.0.1:8085:3000'
    environment:
      TZ: Europe/Vienna
      DB_USER: CHANGEME
      DB_PASS: CHANGEME
      DB_HOST: 'mongo'
    restart: unless-stopped
