version: '3'
services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: astro
    ports:
      - '127.0.0.1:8085:8085'
    environment:
      # DB_PATH: './'
      TZ: Europe/Vienna
    restart: unless-stopped
