version: '3.9'
services:
  dragonfly-dev:
    image: ghcr.io/dragonflydb/dragonfly:latest
    hostname: dragonfly
    environment:
      TZ: Europe/Vienna
    ports:
      - '127.0.0.1:6379:6379'
    restart: unless-stopped
    profiles:
      - dev
