version: '3'
services:
  proxy:
    image: nginx:latest
    hostname: proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./proxy/conf:/etc/nginx/conf.d
      - ./proxy/ssl:/etc/ssl/private
    environment:
      TZ: Europe/Vienna
    restart: unless-stopped
  astro:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: astro
    ports:
      - '127.0.0.1:8085:8085'
    volumes:
      - './data:/var/lib/denokv'
    environment:
      TZ: Europe/Vienna
    restart: unless-stopped
