apiVersion: v1
kind: Pod
metadata:
  labels:
    app: blog
  name: blog
spec:
  securityContext:
    fsGroup: 1000
    privileged: false
    readOnlyRootFilesystem: false
  containers:
  - image: blog:latest
    name: server
    env:
    - name: TZ
      value: Europe/Vienna
    - name: POSTS_PATH
      value: /posts
    - name: DB_HOST
      value: db
    ports:
    - containerPort: 8080
      hostIP: 127.0.0.1
      hostPort: 8880
    volumeMounts:
    - mountPath: /posts
      name: data-posts
  - image: docker.io/library/redis:7-alpine
    name: db
    env:
    - name: TZ
      value: Europe/Vienna
    volumeMounts:
    - mountPath: /data
      name: data-db
  volumes:
  - hostPath:
      path: ./posts
      type: DirectoryOrCreate
    name: data-posts
  - hostPath:
      path: ./database
      type: DirectoryOrCreate
    name: data-db
