apiVersion: v1
kind: Pod
metadata:
  labels:
    app: k1f0dev
  name: k1f0dev
spec:
  securityContext:
    fsGroup: 1000
    privileged: false
    readOnlyRootFilesystem: false
  containers:
  - args:
    - nginx
    - -g
    - daemon off;
    env:
    - name: TZ
      value: Europe/Vienna
    image: k1f0dev:latest
    name: website
    ports:
    - containerPort: 80
      hostIP: 127.0.0.1
      hostPort: 8880
