apiVersion: v1
kind: Pod
metadata:
  labels:
    app: blog
  name: blog
spec:
  securityContext:
    fsGroup: 1000
    privileged: false
    readOnlyRootFilesystem: false
  containers:
  - args:
    - nginx
    - -g
    - daemon off;
    env:
    - name: TZ
      value: Europe/Vienna
    image: k1f0dev-blog:latest
    name: server
    ports:
    - containerPort: 8080
      hostIP: 127.0.0.1
      hostPort: 8880
