apiVersion: v1
kind: Pod
metadata:
  labels:
    app: k1f0dev-pod
  name: k1f0dev-pod
spec:
  securityContext:
    fsGroup: 1000
    privileged: false
    readOnlyRootFilesystem: false
  containers:
  - args:
    - nginx
    - -g
    - daemon off;
    env:
    - name: TZ
      value: Europe/Vienna
    image: k1f0dev:latest
    name: nginx
    ports:
    - containerPort: 443
      hostPort: 443
    - containerPort: 80
      hostPort: 80
    volumeMounts:
    - mountPath: /etc/nginx
      name: nginx-0
    - mountPath: /etc/ssl/private
      name: ssl-0
  volumes:
  - hostPath:
      path: ./nginx
      type: DirectoryOrCreate
    name: nginx-0
  - hostPath:
      path: ./ssl
      type: DirectoryOrCreate
    name: ssl-0
