apiVersion: v1
kind: Pod
metadata:
  labels:
    app: k1f0dev
  name: k1f0dev
spec:
  securityContext:
    fsGroup: 1000
    privileged: false
    readOnlyRootFilesystem: false
  containers:
  - image: home:latest
    name: home
    env:
    - name: TZ
      value: Europe/Vienna
    - name: CONFIG
      value: /config/config.json
    ports:
    - containerPort: 8080
      hostIP: 127.0.0.1
      hostPort: 8881
    volumeMounts:
    - mountPath: /config
      name: data-home-config
    - mountPath: /icons
      name: data-icons
  - image: blog:latest
    name: blog
    env:
    - name: TZ
      value: Europe/Vienna
    - name: POSTS_PATH
      value: /posts
    - name: DB_HOST
      value: db
    ports:
    - containerPort: 80
      hostIP: 127.0.0.1
      hostPort: 8880
    volumeMounts:
    - mountPath: /config
      name: data-blog-config
    - mountPath: /posts
      name: data-posts
  - args:
    - valkey-server
    - --save 60 1
    - --loglevel warning
    image: docker.io/valkey/valkey:8-alpine
    name: db
    env:
    - name: TZ
      value: Europe/Vienna
    volumeMounts:
    - mountPath: /data
      name: data-db
  volumes:
  - hostPath:
      path: ./posts
      type: DirectoryOrCreate
    name: data-posts
  - hostPath:
      path: ./icons
      type: DirectoryOrCreate
    name: data-icons
  - hostPath:
      path: ./blog_config
      type: DirectoryOrCreate
    name: data-blog-config
  - hostPath:
      path: ./home_config
      type: DirectoryOrCreate
    name: data-home-config
  - hostPath:
      path: ./database
      type: DirectoryOrCreate
    name: data-db
