# from node 22 slim
FROM node:22-slim as builder

# change workdir
WORKDIR /build

# Copy initial necessary files to container
COPY package.json \
    astro.config.mjs \
    tsconfig.json \
    ./

# Install dependencies
RUN npm install --omit=dev

# Copy all other files
COPY src ./src

# build
RUN npm run build

# from node 22 slim
FROM node:22-slim

# Set working directory
WORKDIR /app

# create necessary paths
RUN mkdir -p /config

# copy app files
COPY --from=builder /build/package.json /app
COPY --from=builder /build/dist /app/dist
COPY --from=builder /build/node_modules /app/node_modules

# symlink images path
RUN ln -s /app/dist/client/icons /icons

# copy misc files
COPY misc/config.json /config

# expose 80
EXPOSE 80

# serve nginx
CMD ["npm", "run", "dist"]
