export const SITE = {
  website: "https://k1f0.dev/",
  author: "k1f0",
  realName: "Fabian",
  profile: "",
  desc: "A minimal, responsive and SEO-friendly Astro blog theme.",
  title: "k1f0.dev",
  ogImage: "",
  lightAndDarkMode: true,
  postPerIndex: 3,
  postPerPage: 5,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Europe/Vienna",
} as const;
